repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        name: ruff (linting)
      - id: ruff-format
        name: ruff (formatting)
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false
        args: ["formkit_ninja"]
      - id: check-formatting
        name: Check formatting
        entry: uv run ruff format --check
        language: system
        types: [python]
        pass_filenames: true
        args: ["--"]
      - id: check-linting
        name: Check linting
        entry: uv run ruff check
        language: system
        types: [python]
        pass_filenames: true
        args: ["--"]